DROP DATABASE IF EXISTS MENTALHEALTH_DB;
CREATE DATABASE IF NOT EXISTS MENTALHEALTH_DB;

USE MENTALHEALTH_DB;

CREATE TABLE ResetPasswordCodes (
    email VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    expiration DATETIME NOT NULL
);
