CREATE TABLE Publications (
    id_publication INT AUTO_INCREMENT PRIMARY KEY,   
    username VARCHAR(50) NOT NULL,                   
    p_titre TEXT NOT NULL,                            
    texte TEXT NOT NULL,                              
    date DATETIME DEFAULT CURRENT_TIMESTAMP,          
    statut ENUM("anonyme", "public") DEFAULT 'public',
    nb_reponses INT DEFAULT 0,                        
    nb_reaction INT DEFAULT 0,                        
    images LONGBLOB,        
